[setup]
boxlength        = 30
zstart           = 120
levelmin         = 6
levelmin_TF      = 6
levelmax         = 6
padding          = 8
overlap          = 4
ref_center       = 0.5, 0.5, 0.5
ref_extent       = 1.0, 1.0, 1.0
align_top        = no
baryons          = yes
use_2LPT         = no
use_LLA          = no
periodic_TF      = yes
blocking_factor  = 8

[cosmology]
Omega_m          = 0.31330923051184745
Omega_L          = 0.6866907694881526
Omega_b          = 0.049309230511847414
H0               = 67.4
sigma_8          = 0.8227686193118336
nspec            = 0.96605
w0               = -1.0
wa               = 0.0

transfer          = camb_file
transfer_file = /home/hafiz/MUSIC_wang/runs_velocity_routing_test/sfdm_wave_col11_x2.dat

[random]
seed[6]           = 12345

[output]
format            = nyx
filename = /home/hafiz/MUSIC_wang/runs_velocity_routing_test/IC_COL11_X2

[poisson]
fft_fine          = yes
accuracy          = 1e-5
pre_smooth        = 3
post_smooth       = 3
smoother          = gs
laplace_order     = 6
grad_order        = 6
